may_Django/test2/test2/urls.py
from django.conf.urls import url
from django.contrib import admin
from books import views
from news.views import area

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',views.index),
    # url(r'^area/(.*)/', area),
    url(r'^area/',area),

]

may_Django/test2/books/models.py
from django.db import models

# Create your models here.
class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateField()
    bread = models.IntegerField(default=0)
    bcomment = models.IntegerField(default=0)
    isDelete = models.BooleanField(default=False)
class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField(default=False)
    isDelete = models.BooleanField(default=False)
    hcomment = models.CharField(max_length=200)
    hbook = models.ForeignKey('BookInfo')
class Practice(models.Model):
    pId = models.IntegerField(primary_key=True)
    pName = models.CharField(max_length=20)
    pAge = models.IntegerField()
    pGender = models.BooleanField(default=False)
    pAddress = models.CharField(max_length=50)
    pPhone = models.CharField(max_length=11,null=True)
    pSalary = models.DecimalField(max_digits=8,decimal_places=2)
    pSection = models.CharField(max_length=20)



'''
INSERT INTO books_practive
VALUES  (10001,'张朝阳',36,1,'北京朝阳区','18018640012',10000,'网络部'),
(10003,'李婷',20,0,'北京房山区','18008640012',9000,'网络部'),
(10005,'钱有才',25,1,'北京海淀区','18008640012',11000,'移动事业部'),
(10006,'赵丽',23,0,'北京朝阳区','18008640012',20000,'公关部'),
(10007,'张亮',30,1,'北京西城区','18008640012',5000,'保卫部'),
(10002,'张阳',28,1,'北京朝阳区','null',12000,'网络部'),
(10004,'李娜',30,0,'北京通州区','null',7000,'人事部');
'''

may_Django/test2/news/models.py
from django.db import models

# Create your models here.
class NewsManager(models.Manager):
    def add_column(self,ntitle1=None,ncontent1=None):
        news = self.model()
        news.ntitle = ntitle1
        news.ncontent = ncontent1
        # news.ntype.add(obj)   添加关系行不通
        news.save()
        return news


class TypeInfo(models.Model):
    tname = models.CharField(max_length=20)
#多对多关系
class NewsInfo(models.Model):
    ntitle = models.CharField(max_length=60)
    ncontent = models.TextField()
    npub_date = models.DateTimeField(auto_now_add=True)
    ntype = models.ManyToManyField('TypeInfo')
    aa = NewsManager()

# b = TypeInfo.objects.filter(newsinfo__ntitle__contains='路人')   可以找到
# b = NewsInfo.objects.filter(ntype__tname__contains='社')  写ntype
# b.ntype  b.ntype_set  找不到  这里返回的是一个多表关联类 相当于 objects 封装了和很多方法 如add() get()
# aa=b.ntype.get() 这样会找到
# b = NewsInfo.objects.get(id=1)
# c = TypeInfo.objects.get(id=2)
# b.ntype.add(c)  使用多表关联字段   在关联表中添加一个新的关联
# b.ntype.remove(c)  删除





# 网上 多关联
# class Goods(models.Model):
#     gname = models.CharField(max_length=20)
#     gprice = models.DecimalField(max_digits=5,decimal_places=2)
#     gcategory = models.ForeignKey('Category',null=True,on_delete=models.SET_NULL)
# class Category(models.Model):
#     cname = models.CharField(max_length=20)
#
# class Store(models.Model):
#     sname = models.CharField(max_length=30)
#     sdetail = models.TextField(blank=True,null=True)
#     scategory = models.ManyToManyField('Category')
#自定义管理员
class Mymanager(models.Manager):
    #定义自己的方法  获得所有省 和直辖市
    def get_all_sheng(self):
        return super().filter(aparent__isnull=True)



#自关联
class AreaInfo(models.Model):
    atitle = models.CharField(max_length=30)
    aparent = models.ForeignKey('self',null=True,blank=True,on_delete=models.SET_NULL,default='110')  #on_delete 主表删除 从表为空
    area = Mymanager()

may_Django/test2/order_detail/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    CustomerId = models.IntegerField(primary_key=True)
    CustomerName = models.CharField(max_length=10)
    CustomerAddr = models.CharField(max_length=50)
    CustomerCity = models.CharField(max_length=10)
class OrderTable(models.Model):
    OrderId = models.IntegerField(primary_key=True)
    OrderDate = models.DateTimeField(auto_now_add=True)
    CustomerId = models.ForeignKey('Customer')

class Product(models.Model):
    ProductId = models.IntegerField(primary_key=True)
    UnitPrice = models.DecimalField(max_digits=5,decimal_places=2)
    ProductName = models.CharField(max_length=20)
class OrderDetail(models.Model):
    # orderId = models.IntegerField(primary_key=True)
    # productId = models.IntegerField(primary_key=True)
    OrderId = models.ForeignKey('OrderTable')
    ProductId = models.ForeignKey('Product')
    Discount = models.DecimalField(max_digits=2,decimal_places=1)
    Quantity = models.IntegerField()

    class Mate:
        #设置两个字段组合在一起是唯一的
        unique_together = ("OrderId", "ProductId")

may_Django/test2/books/views.py
from django.shortcuts import render
from .models import BookInfo,Practice
from django.db.models import F,Q

# Create your views here.
def index(request):
    # result = BookInfo.objects.all()
    # result = BookInfo.objects.filter(id__exact=2)
    #contains :是否包含
    # result = BookInfo.objects.filter(btitle__contains='射')
    # result = Practice.objects.all()
    #升序
    # result1 = Practice.objects.order_by()
    #降序
    # result1 = Practice.objects.order_by('-pSalary')
    # F 属性和属性的对比

    result = BookInfo.objects.filter(bread__gt=F('bcomment'))
    result1 = Practice.objects.filter(pPhone__isnull=True)

    # result = BookInfo.objects.get(pk=1)

    vv = {'list':result,'list1':result1}
    return render(request,'index1.html',vv)

may_Django/test2/news/views.py
from django.shortcuts import render
from .models import AreaInfo
# Create your views here.
def area(request,**val):
    # lone = AreaInfo.objects.all()
    # list = lone[0]
    if val == None:
        list = AreaInfo.area.filter(aparent__isnull=True)
    else:
        list = AreaInfo.area.filter(atitle__contains=val['username'])
    aa = {'list':list}
    return render(request,'area.html',aa)

may_Django/test2/order_detail/views.py
from django.shortcuts import render

# Create your views here.

may_Django/test2/templates/area.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>地区自关联</title>
</head>
<body>
<h1>输入地区查找他的上级或下级</h1>

<from method="get" action="/area">
    <label for="um">输入地区</label>
        <!-- value是默认值，提示信息用：placeholder="用户名/邮箱/手机号" -->
        <input id="um" type="text" name="username" value="我是value"><br>
        <input type="submit" value="提交" />
    </from>





{#    <div>当前地区:{{ list.atitle }}</div>#}
{#    <div>上级地区:{{ list.aparent_id}}</div>#}
    <ul>
        所有省:
        {% for area in list%}

            <li>{{ area.atitle }}</li>
{#        下级县:#}
{#            <li>{{ area.areainfo_set.get.atitle }}</li>#}
        {% endfor %}
    </ul>

</body>
</html>

may_Django/test2/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>蘑菇街</title>
    <script>
        {#var name = 'aa';#}
        function func() {
            var name = 'bb';
            function inner(){
                alert(name)
            }
            return inner;

        }
        var ret = func()
        ret()

    </script>
    <style type="text/css">
		table{
			/*设置表格的宽度*/
			{#width: 300px;#}
			/*居中*/
			margin: 0 auto;
			/*边框*/
            /*border:1px solid black;*/
            /*table和td边框之间默认有一个距离，通过border-spacing属性可以设置这个距离*/
            /*border-spacing: 10px;*/
            /*
            border-collapse可以用来设置表格的边框合并
            如果设置了边框合并，则border-spacing自动失效
            */
            border-collapse: collapse;
            /*设置背景样式*/
			/*background-color: #bfa;*/
		}
		/*设置边框*/
		th, td{
			border: 1px solid black;
		}
		/*设置隔行变色*/
		tbody > tr:nth-child(even){
			background-color: #bfa;
		}
		/*鼠标移入到tr以后，改变颜色*/
		tr:hover{
			background-color: yellow;
		}
	</style>
</head>
<body>
<table border="1" width="40%" align="center">

        <!-- 在tr中需要使用td来创建一个单元格，有几个单元格就有几个td -->
{% for book  in list %}
     <tr>
         <td>{{ book.pId }}</td>
         <td>{{ book.pName }}</td>
         <td>{{ book.pAge }}</td>
         <td>{{ book.pGender }}</td>
         <td>{{ book.pAddress }}</td>
         <td>{{ book.pPhone }}</td>
         <td>{{ book.pSalary }}</td>
         <td>{{ book.pSection }}</td>
         <td>{{ book.btitle }}</td>

    </tr>
{% endfor %}

</table>
{% for g in list1 %}
    <h2>{{ g.pName }}</h2>
{% endfor %}


</body>
</html>